language: R
sudo: no
cache: packages

python:
  - "3.6"

before_script:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - ls ~/virtualenv/  
  - ls ~/virtualenv/python3.6
  - ls ~/virtualenv/python3.6/bin
  - . ~/virtualenv/python3.6/bin/activate
  - setup_python 3.6 ;

after_success: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
    then 
      travis_wait 100 Rscript -e 'covr::codecov(type = "all")'; 
    fi

warnings_are_errors: yes
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: --as-cran --install-args=--build
deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: flexconn*.t*gz
  'on':
    tags: yes
    repo: muschellij2/flexconn

