language: R
sudo: no
cache: packages

os:
  - linux
  - osx

python: 3.5
  
before_script:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}  
  - install_python_requirements ;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; 
    then 
      echo $USER ;
      ls /Library/Frameworks/Python.framework/Versions/;
      export CI_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION; 
    fi
  # - version=3.6
  # - export TRAVIS_PYTHON_VERSION="${version}"
  # - PYENV_PATH_FILE='/etc/profile.d/pyenv.sh'
  # - echo 'export PATH=/opt/python/${version}/bin:$PATH' | sudo tee -a ${PYENV_PATH_FILE} &>/dev/null
  # - virtualenv="python${version}"  
  # - chmod +x ~/virtualenv/"${virtualenv}"/bin/activate
  # - source ~/virtualenv/"${virtualenv}"/bin/activate
  # - setup_python ${version} ;

after_success: 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; 
    then 
      travis_wait 100 Rscript -e 'covr::codecov(type = "all")'; 
    fi

warnings_are_errors: yes
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: --as-cran --install-args=--build
deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: flexconn*.t*gz
  'on':
    tags: yes
    repo: muschellij2/flexconn

