language: R
sudo: no
cache: packages

before_script:
  - pip2.7 install --upgrade --ignore-installed --user numpy scipy


after_success: if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'covr::codecov(type
  = "all")'; fi
warnings_are_errors: yes
before_deploy: if [ "$TRAVIS_OS_NAME" == "osx" ]; then rm -f *.tar.gz; fi
r_check_args: --as-cran --install-args=--build
deploy:
  provider: releases
  skip_cleanup: yes
  file_glob: yes
  file: flexconn*.t*gz
  'on':
    tags: yes
    repo: muschellij2/flexconn

